homeassistant:
  name: Otthon
  latitude: 46.83410755425139
  longitude: 16.82719535200499
  elevation: 152
  unit_system: metric
  time_zone: Europe/Budapest
 

influxdb:
  host: addon_a0d7b954_influxdb
  port: !secret influxdbprt
  database: home_assistant
  username: !secret influxdbusr
  password: !secret influxdbpw
  max_retries: 3
  default_measurement: state
          
recorder:
cloud:
discovery:
hassio:

homekit:
  filter:
    include_domains:
      - light
      - media_player
      - binary_sensor
      - climate
      - fan
      - switch
      - lock
      - sensor
      - input_boolean

frontend:
  themes:
    cold:
      primary-text-color: '#447ebc'
      label-badge-red: '#447ebc'
    comfortable:
      primary-text-color: '#629e51'
      label-badge-red: '#629e51'
    hot:
      primary-text-color: '#bf1b00'
      label-badge-red: '#bf1b00'

camera:
  - platform: ffmpeg
    input: 'rtsp://10.10.1.140:6554/user=whit33r&password=basH3Rfr&channel=1&stream=0.sdp?real_stream--rtp-caching=100'
    name: Bejárat Kamera

    
#ffmpeg:
#  ffmpeg_bin: /usr/bin/ffmpeg

config:

climate:
  - platform: generic_thermostat
    name: Szoba Termosztát
    heater: switch.szoba_futopanel
    target_sensor: sensor.homerseklet_szoba

http:
   api_password: !secret http_password
   ssl_certificate: /ssl/fullchain.pem
   ssl_key: /ssl/privkey.pem
#   base_url: !secret url

mqtt:
  broker: localhost
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant

media_player:
  - platform: kodi
    host: 10.10.0.128
  - platform: yamaha
    host: 10.10.1.17
    source_ignore:
      - "AUX"
      - "HDMI6"
      - "USB"
      - "TUNER"
      - "SERVER"
      - "Qobuz"
      - "NET RADIO"
      - "JUKE"
      - "HDMI1"
      - "HDMI3"
      - "HDMI4"
      - "AUDIO1"
      - "AUDIO2"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AUX"
      - "AirPlay"
      - "Bluetooth"
      - "MusicCast Link"
    source_names:
      HDMI2: "FireTV Stick"

notify:
  - name: pushover-noti
    platform: pushover
    api_key: !secret notifyapi
    user_key: !secret notifykey
  - name: MariIosApp
    platform: ios
    target: 1fc596fb-05e2-33a7-b6f9-1dc1b04a8b9d
    
input_boolean:
  me_present:
    name: Me
    icon: mdi:account
  mom_present:
    name: Mom
    icon: mdi:account

emulated_hue:
  host_ip: 10.10.0.22
  listen_port: 8300
  off_maps_to_on_domains:
    - script
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - script

updater:
   include_used_components: true
conversation:
history:
logbook:
map:
sun:
alexa:

automation: !include automation.yaml
#script: !include scripts.yaml
sensor: !include sensors.yaml
light: !include light.yaml
binary_sensor: !include binary_sensor.yaml
switch: !include switch.yaml
script: !include script.yaml
group: !include group.yaml
ios: !include ios.yaml
device_tracker: !include device_tracker.yaml
customize: !include customize.yaml
