homeassistant:
  name: Otthon
  latitude: 46.83410755425139
  longitude: 16.82719535200499
  elevation: 152
  unit_system: metric
  time_zone: Europe/Budapest
  customize: !include customize.yaml
  
conversation:
history:
logbook:
map:
sun:
alexa:
#lyric:
#  client_id: WL7rnI60g7mDFT9jVRjGrvkH8GG4EZao
#  client_secret: budOAFDirseBjiD6

influxdb:
  host: addon_a0d7b954_influxdb
  port: !secret influxdbprt
  database: home_assistant
  username: !secret influxdbusr
  password: !secret influxdbpw
  max_retries: 3
  default_measurement: state

apple_tv:
  - host: 10.10.1.181
    login_id: 00000003-bd3e-9ff2-d106-ce803e1b4ca9
    credentials: 91E6A768D456A33A:5AFBC05A04334F47F1EAA32BE9A6C46403841C79347ED4129D98F76DD3B1B9BB
    
panel_iframe:
  nodered:
    title: Node-RED
    icon: mdi:sitemap
    url: !secret noderedurl
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ideurl
    
cloud:
discovery:
  enable: 
    - homekit
hassio:

homekit:
  filter:
    include_entities:
      - light.0x000b57fffe8a0038_light
      - light.0x000b57fffe9757aa_light
      - light.0x000b57fffed99840_light
      - light.0x90fd9ffffe0f74af_light
      - light.0x000b57fffed8512d_light
      - light.0x000b57fffe9757aa_light
      - light.0xd0cf5efffe7a08f7_light
      - binary_sensor.0x00158d0002cb42ee_occupancy
      - light.ablak_dekoracio
      - light.fuggony_vilagitas
      - light.karacsonyfa
      - light.konyha_vilagitas
      - light.szoba_vilagitas
      - climate.szoba_termosztat
      - binary_sensor.bejarati_ajto
      - binary_sensor.bejarati_ajto_zar
      - input_boolean.zigbee_permit_join
      - script.mozi_bekapcsolasa
      - script.mozi_kikapcsolasa
      - sensor.homerseklet_konyha
      - sensor.homerseklet_kulso
      - sensor.homerseklet_szoba
  entity_config:
    light.0x000b57fffe8a0038_light:
      name: Tükrös Lámpa
    light.0x000b57fffe9757aa_light:
      name: Fürdő Világitás
    light.0x000b57fffed99840_light:
      name: Állólámpa
    light.0x90fd9ffffe0f74af_light:
      name: Folyosó Extra
    light.0x000b57fffed8512d_light:
      name: Folyosó Világitás
    light.0x000b57fffe9757aa_light:
      name: WC Világitás
    light.ablak_dekoracio:
      name: Ablak Dekoráció
    light.fuggony_vilagitas:
      name: Hangulatfény
    light.konyha_vilagitas:
      name: Konyha Világitás
    binary_sensor.0x00158d0002cb42ee_occupancy:
      name: Konyha Motion
      

frontend: !include frontend.yaml

    
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

config:

climate:
  - platform: generic_thermostat
    name: Szoba Termosztát
    heater: switch.szoba_futopanel
    target_sensor: sensor.homerseklet_szoba

http:
   api_password: !secret http_password
   ssl_certificate: /ssl/fullchain.pem
   ssl_key: /ssl/privkey.pem
   base_url: https://whiterhass.duckdns.org

mqtt:
  broker: localhost
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant


    
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600 # Updated this to the number of seconds you wish

media_player:
#  - platform: kodi
#    host: 10.10.0.128
  - platform: yamaha
    host: 10.10.1.17
    source_ignore:
      - "AUX"
      - "HDMI6"
      - "USB"
      - "TUNER"
      - "SERVER"
      - "Qobuz"
      - "NET RADIO"
      - "JUKE"
      - "HDMI1"
      - "HDMI3"
      - "HDMI4"
      - "AUDIO1"
      - "AUDIO2"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AUX"
      - "AirPlay"
      - "Bluetooth"
      - "MusicCast Link"
    source_names:
      HDMI2: "FireTV Stick"

notify:
  - name: pushover-noti
    platform: pushover
    api_key: !secret notifyapi
    user_key: !secret notifykey
  - name: iosferi
    platform: ios
    target: 82fb16ae-ff77-35db-a7e0-8ca32114d6ad
  - name: iosmom
    platform: ios
    target: 1fc596fb-05e2-33a7-b6f9-1dc1b04a8b9d
    
input_boolean:
  me_present:
    name: Me
    icon: mdi:account
  mom_present:
    name: Mom
    icon: mdi:account
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

emulated_hue:
  host_ip: 10.10.0.22
  listen_port: 8300
  off_maps_to_on_domains:
    - script
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - script

updater:
   include_used_components: true


automation: !include automation.yaml
#script: !include scripts.yaml
sensor: !include sensors.yaml
light: !include light.yaml
binary_sensor: !include binary_sensor.yaml
switch: !include switch.yaml
script: !include script.yaml
group: !include group.yaml
ios: !include ios.yaml
device_tracker: !include device_tracker.yaml
camera: !include camera.yaml
panel_custom: !include panel_custom.yaml